sudo: false
language: rust
rust:
- nightly
- beta
- stable
matrix:
  allow_failures:
  - rust: nightly
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
before_script:
- ! 'pip install ''travis-cargo<0.2'' --user &&

  export PATH=$HOME/.local/bin:$PATH

'
script:
- ! 'cargo build &&

  cargo test &&

  travis-cargo --only stable doc

'
after_success:
- ! 'travis-cargo --only stable doc-upload &&

  travis-cargo --only stable coveralls --no-sudo

'
env:
  global:
    secure: H62BbcY6uJ5ejzGa3feXzrLwiWwlGFNUstAPNZdAuxX1yS2woQc9Zkj7FFnFCDoU4VMRJHerpaAVr4TsUhiF5nGYbc6zTZyr0EOyQwFwnWK5Deu1ooBtf8CjTKOqzqP8xfn95JyhAIOlnFz65BrnuRqXakZQF0RXlwjzU2RrifGqjmRfNFxRPN9XhLlDlXjSIsEf3RwZlMKyvJ1NaR1A5Pa7OBmSoAnDQa8ptoW+hjzGhZUyJUY1dkMJPBrTRoBixf42BVXU/oG9T1SzDIqQLnwxv78apikA/iP9bihhtHlOVq0ZIteRupkf39NUVPkQDOD1yj7L/6QujXAf0TZ2VGofwGnPIIqAqsuGT7JfJNVuPqxBJbYON0uFA4QoWIlaYTq7aTqE9/Vecb1deLgcLSKmSG/WANp/pbcjw85tABdBvTcJjDbMz0A/xedOZAfCLzXITpRCMcDQZPsIrtWHfRe4390OyLdz61d47HABy58/xOOOA0jeLDoKM57O/bJOwfuooVf1O5pzEclCynHgUvNWzwfwnMKr967cr/BSHzyoqZ5RVz/Itg36KbnJ9xF+SCTwl3g55SCixnmaSGSudh9gknExZNyyVZMyqzKXcJXf6RAjFf1gUDYBr5JAtqh0Aoz3J1eXPc5yFox++nnq3cue5uZY4uYRxiGPmEbHyqQ=
